name: PR - unit testing with jest
on:
  push:
      branches:
        - master
jobs:
  publish:
    name: Unit Test
    runs-on: ubuntu-latest,
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn jest
    