name: PR - unit testing with jest
on:
  push:
      branches:
        - master
  pull_request:
      branches: [ master ]
jobs:
  publish:
    name: Unit Test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn jest
    